version: 2.1

jobs:
  mini-ci-job:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout

      - run:
          name: Compile Java Code
          command: javac Hello.java

      - run:
          name: Run Java Program
          command: java Hello

      - store_artifacts:
          path: Hello.class

workflows:
  mini-ci-workflow:
    jobs:
      - mini-ci-job
