version: 2.1

jobs:
  simple-pipeline:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout

      - run:
          name: Build stage
          command: echo "Building the application"

      - run:
          name: Test stage
          command: echo "Running tests"

workflows:
  simple-workflow:
    jobs:
      - simple-pipeline
