version: 2.1

jobs:
  java-build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout

      - run:
          name: Compile Java program
          command: javac Hello.java

      - run:
          name: Run Java program
          command: java Hello

      - store_artifacts:
          path: Hello.class


workflows:
  java-workflow:
    jobs:
      - java-build
