version: 2.1

jobs:
  Hello-CircleCI:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Show source code files
          command: ls
      - run:
          name: Print Hello Message
          command: echo "Hello CircleCI"

workflows:
  hello-workflow:
    jobs:
      - Hello-CircleCI
