version: 2.1

parameters:
  username:
    type: string
    default: "Srilaya"

jobs:
  Hello-CircleCI:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Print USERNAME parameter
          command: echo "Username is Srilaya"

workflows:
  hello-workflow:
    jobs:
      - Hello-CircleCI
